export const FETCHING_DWARFPLANET_DATA = 'FETCHING_DWARFPLANET_DATA';
export const FETCHING_DWARFPLANET_DATA_SUCCESS = 'FETCHING_DWARFPLANET_DATA_SUCCESS';
export const FETCHING_DWARFPLANET_DATA_FAILURE = 'FETCHING_DWARFPLANET_DATA_FAILURE';