export const FETCHING_PLANET_DATA = 'FETCHING_PLANET_DATA';
export const FETCHING_PLANET_DATA_SUCCESS = 'FETCHING_PLANET_DATA_SUCCESS';
export const FETCHING_PLANET_DATA_FAILURE = 'FETCHING_PLANET_DATA_FAILURE';